language: php
php:
  - 5.4
  - 5.5
  - 5.6
  
env:
  - SYMFONY_VERSION="2.3.*" DB=mysql
  - SYMFONY_VERSION="2.7.*" DB=mysql
  - SYMFONY_VERSION="dev-master" DB=mysql
  
install:
  - composer self-update
  - composer require symfony/symfony:${SYMFONY_VERSION} --prefer-source
  
script: phpunit
